name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  
  pull-request-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_14.3.app

          
      - name: Install MAUI Workloads for macOS
        if: matrix.os == 'macos-latest'
        run: |
          dotnet workload install maccatalyst --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources
          
      - name: Install MAUI Workloads for Windows
        if: matrix.os == 'windows-latest'
        run: |
          dotnet workload install maui --ignore-failed-sources

      - name: Restore dependencies
        run: dotnet restore source/
        
      - name: Build and analyze
        shell: pwsh
        run: |
          dotnet build  source/ -c Release -f net6.0-maccatalyst --no-restore
          dotnet test source/
