name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  
  pull-request-check:
    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install .NET MAUI
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore source/
        
      - name: Build and analyze
        shell: pwsh
        run: |
          dotnet build --configuration Release --no-restore source/
          dotnet test source/
